
language: python

python:
    - "3.6"
services:
    - postgresql
    
install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - nosetests app/tests/ --with-coverage

before_script:
    - psql -c 'CREATE DATABASE test_ride_my_way;' -U postgres

after_success:
    - coveralls
